name: Testing Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          checkout-fetch-depth: 0
          java-version: 21
          maven-version: 3.9.5

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          checkout-fetch-depth: 0
          java-version: 21
          maven-version: 3.9.5

      - name: Run Tests
        run: mvn test
